# Generated by Django 4.0.3 on 2022-03-13 01:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id_grupo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
                ('criado', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='clientes.grupos'),
        ),
    ]
