# Generated by Django 4.0.3 on 2022-03-13 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_grupos_criado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.grupos'),
        ),
    ]
