# Generated by Django 2.2.20 on 2022-04-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_grupos_criado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=1),
        ),
    ]
