# Generated by Django 2.2.20 on 2022-04-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20220421_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1),
        ),
    ]
