# Generated by Django 2.2.20 on 2022-04-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20220421_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=50),
        ),
    ]
