# Generated by Django 2.2.20 on 2022-04-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20220422_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Nenhuma das opções', 'Nenhuma das opções')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=10),
        ),
    ]
